### ISSUE TITLE
Everything shows as unrated.

### ISSUE THREAD

**Issue by LostShadowGD** [MigMatos/ObeyGDBrowser#1]
Everything shows as unrated in my browser.

![image](https://github.com/MigMatos/ObeyGDBrowser/assets/156698581/a4507411-b31f-4943-ac12-f4d5dc073843)
![image](https://github.com/MigMatos/ObeyGDBrowser/assets/156698581/442f43f4-cec5-403c-b97b-29af59ea370c)

**Comment by MigMatos** [comment]
Fixed in the version 0.24+
Thx for reporting!
