### ISSUE TITLE
A lot of errors...

### ISSUE THREAD

**Issue by bubzilla** [MigMatos/ObeyGDBrowser#15]
**Describe the bug**
SyntaxError: Identifier 'url' has already been declared at https://[REDACTED].5v.pl/browser/songs/?:318:9

**To Reproduce**
1. Click on literally anything level related on ObeyGDBrowser
2. See error

**Expected behavior**

It working...

**Screenshots**
![screeny](https://github.com/user-attachments/assets/5d0480ba-1dab-46d8-853e-8ed4a85339c8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version no idea

**Additional context**
i did install the browser directly from the repository though so it might be a pre-release or smth

**Comment by bubzilla** [comment]
also should have mentioned im using the MegaSa1nt fork

**Comment by bubzilla** [comment]
also can you add an uninstaller or smth

**Comment by MigMatos** [comment]
Switch to a stable ver

**Comment by bubzilla** [comment]
![Screenshot 2024-10-15 092304](https://github.com/user-attachments/assets/f80dd3b1-cc1f-4442-bc83-c032f465f8ad)

**Comment by MigMatos** [comment]
Fixed in "Unstable versions", 5v.pl Host installs a script that blocks ObeyGDBrowser.
